modLoader = "javafml"
loaderVersion = "[46,)"
clientSideOnly = true
displayURL = "https://www.curseforge.com/minecraft/mc-mods/translatorpp"
issueTrackerURL = "https://github.com/pSUNSET/TranslatorPP/issues"
logoFile = "icon.png"
authors = "Project-SUNSET"
credits = "Everyone who contributed to this mod"
license = "MIT"

[[mods]]
modId = "translatorpp"
version = "${version}"
displayName = "Translator++"
description = '''
A mod for swift, light and convenient auto translation.
'''

[[dependencies.translatorpp]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.translatorpp]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_forge_range}"
ordering = "NONE"
side = "CLIENT"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"
