org.gradle.jvmargs=-Xmx2G

# Mod properties
mod_id=translatorpp
mod_version=2.1.0
maven_group=net.psunset

# Required Common Dependencies
minecraft_version=1.21.10
minecraft_version_fabric_range=>=1.21.9
minecraft_version_neoforge_range=[1.21.9,)

# Optional Common Dependencies
cloth_config_version=20.0.149
modmenu_version=16.0.0-rc.1
jei_version=26.1.0.16
rei_version=20.0.811

# Required Fabric Dependencies
fabric_loader_version=0.17.3
fabric_loader_version_range=*
fabric_api_version=0.138.0
fabric_api_version_range=*

# Optional Fabric Dependencies
jade_fabric_version=20.1.0+fabric

# Required NeoForge Dependencies
neoforge_version=21.10.49-beta
neoforge_version_range=[21.9,)

# Optional NeoForge Dependencies
jade_neoforge_version=20.0.5+neoforge

# Non-mod Libraries
