org.gradle.jvmargs=-Xmx2G

# Mod properties
mod_id=translatorpp
mod_version=2.5.0
maven_group=net.psunset

# Required Common Dependencies
minecraft_version=26.1.2
minecraft_version_file_range=26.1.x
minecraft_version_fabric_range=>=26.1 <26.2
minecraft_version_neoforge_range=[26.1,26.2)
parchment_mappings_version=MISSING

# Optional Common Dependencies
cloth_config_version=26.1.154
jei_version=29.16.0.47
rei_version=26.1.819

# Required Fabric Dependencies
fabric_loader_version=0.19.3
fabric_loader_version_range=*
fabric_api_version=0.151.0
fabric_api_version_range=*

# Optional Fabric Dependencies
modmenu_version=18.0.0-beta.1
jade_fabric_version=26.1.0+fabric

# Required NeoForge Dependencies
neoforge_version=26.1.2.76
neoforge_version_range=[26,)

# Optional NeoForge Dependencies
jade_neoforge_version=26.1.1+neoforge

# Non-mod Libraries
