org.gradle.jvmargs=-Xmx2G

# Mod properties
mod_id=translatorpp
mod_version=2.0.a
maven_group=net.psunset

########## 1.21.1 ##########

## Required Common Dependencies
#minecraft_version=1.21.1
#minecraft_version_fabric_range=>=1.21
#minecraft_version_neoforge_range=[1.21,)
#
## Optional Common Dependencies
#cloth_config_version=15.0.140
#modmenu_version=11.0.3
#jei_version=19.21.2.313
#rei_version=16.0.799
#
## Required Fabric Dependencies
#fabric_loader_version=0.16.14
#fabric_loader_version_range=*
#fabric_api_version=0.115.6
#fabric_api_version_range=*
#
## Optional Fabric Dependencies
#jade_fabric_version=6494189
#
## Required NeoForge Dependencies
#neoforge_version=21.1.168
#neoforge_version_range=[21,)
#
## Optional NeoForge
#jade_neoforge_version=6667790
#
## Non-mod Libraries

########## 1.21.5 ##########

# Required Common Dependencies
minecraft_version=1.21.5
minecraft_version_fabric_range=>=1.21
minecraft_version_neoforge_range=[1.21,)

# Optional Common Dependencies
cloth_config_version=18.0.145
modmenu_version=14.0.0-rc.2
jei_version=21.3.2.22
rei_version=19.0.809

# Required Fabric Dependencies
fabric_loader_version=0.16.14
fabric_loader_version_range=*
fabric_api_version=0.128.1
fabric_api_version_range=*

# Optional Fabric Dependencies
jade_fabric_version=6504606

# Required NeoForge Dependencies
neoforge_version=21.5.81
neoforge_version_range=[21,)

# Optional NeoForge Dependencies
jade_neoforge_version=6524708

# Non-mod Libraries
