modLoader = "javafml"
loaderVersion = "[1,)"
clientSideOnly = true
displayURL = "https://www.curseforge.com/minecraft/mc-mods/translatorpp"
issueTrackerURL = "https://github.com/pSUNSET/TranslatorPP/issues"
logoFile = "icon.png"
authors = "LShiftLess"
credits = "By - LShiftLess (NoodleInWater)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Translator++"
description = '''
A mod for swift, light and convenient auto translation.
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_neoforge_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "${architectury_api_version_neoforge_range}"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
