architectury {
    common('fabric', 'neoforge')
}

loom {
    accessWidenerPath = project(":fabric").file("src/main/resources/translatorpp.accesswidener")
}

dependencies {
    // For using @Environment and EnvType
    compileOnly "net.fabricmc:fabric-loader:$fabric_loader_version"

    compileOnly "me.shedaniel.cloth:cloth-config:$cloth_config_version"

    // JEI, REI, EMI? (Unused)
//    compileOnly "mezz.jei:jei-$minecraft_version-common-api:$jei_version"
//    compileOnly "me.shedaniel:RoughlyEnoughItems-api:$rei_version"

    // Jade (using neoforge)
    compileOnly "maven.modrinth:jade:$jade_neoforge_version"
}
