architectury {
    common('fabric', 'neoforge')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modCompileOnlyApi "net.fabricmc:fabric-loader:$fabric_loader_version"

    modCompileOnlyApi "dev.architectury:architectury:$architectury_api_version"

    modCompileOnlyApi "me.shedaniel.cloth:cloth-config:$cloth_config_version"

    // JEI, REI, EMI?
//    modCompileOnlyApi "mezz.jei:jei-$minecraft_version-common-api:$jei_version"
//    modCompileOnlyApi "me.shedaniel:RoughlyEnoughItems-api:$rei_version"

    // Jade (using fabric)
    modCompileOnlyApi "curse.maven:jade-324717:$jade_fabric_version"
}
