modLoader = "javafml"
loaderVersion = "[1,)"
clientSideOnly = true
displayURL = "https://www.curseforge.com/minecraft/mc-mods/translatorpp"
issueTrackerURL = "https://github.com/pSUNSET/TranslatorPP/issues"
logoFile = "icon.png"
authors = "LShiftLess"
credits = "Everyone who contributed to this mod"
license = "MIT"

[[mods]]
modId = "translatorpp"
version = "${version}"
displayName = "Translator++"
description = '''
A mod for swift, light and convenient auto translation.
'''

[[dependencies.translatorpp]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.translatorpp]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_neoforge_range}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "translatorpp.mixins.json"

[[mixins]]
config = "translatorpp.neoforge.mixins.json"
