plugins {
    id 'com.github.johnrengelman.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:$neoforge_version"

    // Cloth Config
    modCompileOnlyApi "me.shedaniel.cloth:cloth-config-neoforge:$cloth_config_version"

    // JEI, REI, EMI?
//    modCompileOnlyApi "mezz.jei:jei-$minecraft_version-neoforge-api:$jei_version"
//    modCompileOnlyApi "me.shedaniel:RoughlyEnoughItems-api-neoforge:$rei_version"

//    modRuntimeOnly "mezz.jei:jei-$minecraft_version-neoforge:$jei_version"
//    modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:$rei_version"

    // FTB Quests

    // Jade
    modApi "curse.maven:jade-324717:$jade_neoforge_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionNeoForge')
}

processResources {
    inputs.property 'version', "$mod_version"

    filesMatching('META-INF/neoforge.mods.toml') {
        expand([
                version: "$mod_version",
                neoforge_version_range: "$neoforge_version_range",
                minecraft_version_neoforge_range: "$minecraft_version_neoforge_range",
        ])
    }
}

jar {
    manifest {
        attributes([
                'Specification-Title'     : "$mod_id",
                'Specification-Vendor'    : "Project SUNSET",
                'Specification-Version'   : "1",
                'Implementation-Title'    : this.project.name,
                'Implementation-Version'  : this.project.jar.archiveVersion,
                'Implementation-Vendor'   : "Project SUNSET",
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    input.set shadowJar.archiveFile
}
